palette = 'rosepine'

format = """
$directory\
$git_branch\
$git_status\
$git_state\
$git_metrics\
$character
"""

right_format = """
$docker_context\
$package\
$c\
$golang\
$haskell\
$java\
$nodejs\
$zig\
$golang\
$python\
$bun\
$lua\
$rust\
"""

[palettes.rosepine]
pine = "#3e8fb0"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#2a283e"
highlight_med = "#44415a"
highlight_high = "#56526e"
rose = "#ea9a97"
text = "#e0def4"
love = "#eb6f92"
subtle = "#908caa"
base = "#232136"
surface = "#2a273f"
overlay = "#393552"
gold = "#ea9d34"


[directory]
style = "bold iris"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](pine)[❯](foam)[❯](text)"
error_symbol = "[❯](love)[❯](rose)[❯](text)"
vicmd_symbol = "[❮](pine)[❮](foam)[❮](text)"

[git_branch]
symbol = ""
style = "bold gold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold pine"
format = '[$all_status$ahead_behind ]($style)'

[git_state]
style = "bold text"
cherry_pick = '[ - PICKING](love)'
rebase = '[ REBASING](gold)'
merge = '[󰽜 - MERGING](iris)'
revert = '[ - REVERTING](love)'
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = 'bold pine'
deleted_style = 'bold love'
format = '[+$added]($added_style) [-$deleted]($deleted_style) '

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bold foam"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bold bold foam"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bold bold foam"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bold bold foam"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bold bold foam"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = ""
style = "bold bold foam"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bold bold foam"
format = '[ $symbol ($version) ]($style)'

[docker_context]
style = 'bold cyan'
format = '[  $context]($style) '

[lua]
style = "bold cyan"
format = '[󰢱  $version]($style) '

[python]
format = "[$symbol$version( \\(venv:$virtualenv\\))]($style) "
version_format = "${raw}"
style = "bold bright-yellow"

[package]
symbol = " "
style = "bold cyan"
disabled = false
display_private = true
format = '[$symbol$version]($style) '

[fill]
symbol = " "
style = 'bold green'

[status]
symbol = ' '
map_symbol = true
style = 'bold fg:cyan'
success_symbol = ''
format = '[$symbol](yellow)$status ($style)'
