prSections:
  - title: Opened
    filters: is:open
  - title: Mine
    filters: is:open is:pr author:@me
    layout:
      author:
        hidden: true
  - title: Review
    filters: is:open review-requested:@me
    layout:
      repo:
        width: 6
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 80
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

keybindings:
  universal:
  prs:
    - key: O
      builtin: checkout
    - key: m
      command: gh pr merge --admin --repo {{.RepoName}} {{.PrNumber}}
    - key: C
      name: code review
      command: >
        tmux new-window -n octo nvim -c ":silent Octo pr edit {{.PrNumber}}"
    - key: v
      name: approve
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: true
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#B0B3BF"
      warning: "#E0AF68"
      success: "#3DF294"
    background:
      selected: "#1B1B33"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
pager:
  diff: diffnav
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
